// The quotes that rotated under the header, as seeded by the old Sanic setup.py
export const psas: Array<{ content: string, author: string }> = [
  { content: 'I made a game once.', author: 'Catlinman' },
  { content: 'Your humble fishstick and fiendlord.', author: 'Catlinman' },
  { content: 'Professional button presser.', author: 'Catlinman' },
  { content: 'I\'m alright at video games.', author: 'Catlinman' },
  { content: 'Javascript is disabled. Right?', author: 'Catlinman' },
  { content: 'Pngyvazna in ROT13!', author: 'Trif' },
  { content: 'Meister of the Kugelscreibers.', author: 'Trif' },
  { content: 'Half my code is for calculators!', author: 'Trif' },
  { content: '100% photoshoppable.', author: 'Trif' },
  { content: 'My hand is a printer!', author: 'Trif' },
  { content: 'Exception: sleep() returned null', author: 'Trif' },
  { content: '500% more particles than our competitors!', author: 'Trif' },
  { content: 'Probably not a robot.', author: 'Trif' },
  { content: 'Favourite hat is a melon.', author: 'Jan Dolanský' },
  { content: 'I come with lots of *pats*.', author: 'Jan Dolanský' },
  { content: 'My name is Cat but you can call me any time.', author: 'Jan Dolanský' },
  { content: 'Isn\'t a cat actually.', author: 'Jan Dolanský' },
  { content: 'I will break your game.', author: 'Jan Dolanský' },
  { content: 'Internet professional.', author: 'Jan Dolanský' },
  { content: 'Gotta go fast like this website.', author: 'Jan Dolanský' },
  { content: 'This page is served as HTML. Fascinating.', author: 'Jan Dolanský' },
  { content: '*tap tap tap*', author: 'Jan Dolanský' },
  { content: 'No HTML, CSS or JS. Only Bash. Apex of web design.', author: 'Jan Dolanský' },
  { content: 'Friends write these messages for me.', author: 'Jan Dolanský' },
  { content: 'Can basically do anything. Mostly confirmed.', author: 'Jan Dolanský' },
  { content: 'Content aware scale ethusiast.', author: 'Jan Dolanský' },
  { content: 'TOP 10 in \'Riding Club Championships\'.', author: 'Jan Dolanský' },
  { content: 'Mostly safe for work.', author: 'Catlinman' },
  { content: 'The only truly certified sandshark!', author: 'Mixilaxi' },
  { content: 'You should see my other projects.', author: 'Catlinman' },
  { content: 'Uses MS Paint if required.', author: 'Catlinman' },
  { content: 'Fresh from the north coast.', author: 'Catlinman' },
  { content: 'The black wind howls...', author: 'Catlinman' },
  { content: 'Radical dreamer.', author: 'Catlinman' },
  { content: 'Dreaming of a shore bordering another world.', author: 'Catlinman' },
  { content: 'Tornado spinning all day long.', author: 'Catlinman' },
  { content: 'Your personal support for everything.', author: 'Catlinman' },
  { content: 'This page is written in Python.', author: 'Catlinman' },
  { content: 'Forgets to keep up commit streaks.', author: 'Catlinman' },
  { content: 'Writes programs you didn\'t think you needed.', author: 'Catlinman' },
  { content: 'There\'s a script for that.', author: 'Catlinman' },
  { content: 'Coming up with messages like this one is hard.', author: 'Catlinman' },
  { content: 'Buy my mixtape.', author: 'Chantaro' },
  { content: 'Relatable until marriage.', author: 'Chantaro' },
  { content: 'Rated 9 out of 7 for some reason.', author: 'Chantaro' },
  { content: 'Don\'t read this. Oh come on.', author: 'Chantaro' },
  { content: 'This is a girls only zone.', author: 'Chantaro' },
  { content: '*insert message here*', author: 'Chantaro' },
  { content: 'H0w do 1 pr0gr4m', author: 'Chantaro' },
  { content: 'Proud knight of the holy watermelon.', author: 'Kagedreng' },
  { content: 'About to kugelschreiber your wunderbar.', author: 'Kagedreng' },
  { content: 'The hero that just happened to be.', author: 'Kagedreng' },
  { content: 'Your personal bæ.', author: 'Kagedreng' },
  { content: 'Requires more RAM. Download more RAM.', author: 'Kagedreng' },
  { content: 'Master exploiter of games all around.', author: 'Kagedreng' },
  { content: 'How did you get here?', author: 'Kagedreng' },
  { content: 'NO TIME TO EXPLAIN JUST HOVER THIS TEXT.', author: 'Kagedreng' },
  { content: 'May have lost the game once or twice.', author: 'Kagedreng' },
  { content: 'What happens if you hover this text long enough?', author: 'Catlinman' },
  { content: 'Connoisseur of waveforms.', author: 'Catlinman' },
  { content: 'Expert audio spectrum handler.', author: 'Catlinman' },
  { content: 'Verified scrobbler.', author: 'Catlinman' },
  { content: 'Trades in scrobbles for prizes.', author: 'Catlinman' },
  { content: 'You define who I am.', author: 'Catlinman' },
  { content: 'Running on port 24070.', author: 'Catlinman' },
  { content: 'I can design that.', author: 'Catlinman' },
  { content: 'I once heard CSS was a programming language.', author: 'Catlinman' },
  { content: 'Always pushing the limit.', author: 'Catlinman' },
  { content: 'Speaks a few languages other than this one.', author: 'Catlinman' },
  { content: 'Diese Nachricht ist in Deutsch. Frag nicht warum.', author: 'Catlinman' },
  { content: 'Always hopeful for a good internet connection.', author: 'Catlinman' },
  { content: 'Survivor of 3000+ ms ping.', author: 'Catlinman' },
  { content: 'Let\'s get trending on these tables.', author: 'Catlinman' },
  { content: 'You can always count on a layer party in my files.', author: 'Catlinman' },
  { content: 'Puts C# on résumés.', author: 'Catlinman' },
  { content: 'Running on nekodrop.com', author: 'Catlinman' },
]
